stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - lint
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile .

test-job:
  stage: test
  image: ubuntu:20.04
  script:
    - echo "Testing code"

setup:
  stage: lint
  image: python:3.10
  script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install
  artifacts:
    expire_in: 1 hour
    paths:
      - .venv
      
black:
  stage: lint
  image: python:3.10
  needs: [setup]
  script:
    - source .venv/bin/activate
    - black --check src tests

mypy:
  stage: lint
  image: python:3.10
  needs: [setup]
  script:
    - source .venv/bin/activate
    - mypy src tests

pylint:
  stage: lint
  image: python:3.10
  needs: [setup]
  script:
    - source .venv/bin/activate
    - pylint src tests
  allow_failure: true

jinjaninja:
  stage: lint
  image: python:3.10
  needs: [setup]
  script:
    - source .venv/bin/activate
    - jinja-ninja src/app/templates/*.html 

deploy-job:      # This job runs in the deploy stage only on main branch
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
