stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - lint
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile .

test-job:
  stage: test
  image: ubuntu:20.04
  script:
    - echo "Testing code"

black:
  stage: lint
  image: python:3.10
  script:
    - pip install black
    - black --check src tests

mypy:
  stage: lint
  image: python:3.10
  script:
    - pip install mypy types-toml sqlalchemy-stubs
    - mypy src tests

pylint:
  stage: lint
  image: python:3.10
  script:
    - pip install pylint
    - pylint src tests

deploy-job:      # This job runs in the deploy stage only on main branch
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
