[database]
host="localhost"
port="3306"
username="root_user"
password="Test123456"

[stauth]
cookie_name="stauth"
cookie_secret_key="Test123456"
cookie_expiry_days=30  # days

[runpod]
use="false"
api_key=""
endpoint=""