services:
  webserver:
    container_name: webserver
    build: 
      context: .
      dockerfile: ./docker/webserver/Dockerfile
    ports:
      - "8080:5000"
    networks:
      - backend
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure

  database:
    container_name: database
    build: 
      context: .
      dockerfile: ./docker/database/Dockerfile
    expose:
      - 3306
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pTest123456"]
      interval: 5s
      timeout: 30s
      retries: 3
    restart: on-failure
      
  ai:
    container_name: ai
    build: 
      context: .
      dockerfile: ./docker/ai/Dockerfile
    expose:
      - 8000
    restart: on-failure
    networks:
      - backend
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]

networks:
  backend: